version: 2
jobs:
  build:
    machine:
        image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - run: javac CircleCI.java
     # - run: sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
     # - run: sudo docker build -t testapp .
     # - run: sudo docker tag testapp $DOCKER_USER/$DOCKER_REPO:$CIRCLE_BUILD_NUM 
     # - run: sudo docker push $DOCKER_USER/$DOCKER_REPO:$CIRCLE_BUILD_NUM
  


