version: 2
jobs:
  build:
    machine:
        image: circleci/classic:edge
    working_directory: ~/repo
    steps:
      - checkout
      - run: javac CircleCI.java
      - run: sudo docker login -u nagarajuravula -p Nagaraju@1
      - run: sudo docker build -t circleci-test .
      - run: sudo docker tag circleci-test nagarajuravula/circleci-test:$CIRCLE_BUILD_NUM 
      - run: sudo docker push nagarajuravula/circleci-test:$CIRCLE_BUILD_NUM
  


